# Default configuration. To achieve more accuracy in the compass, periodically
# regenerate. With Kingfisher deployed in water, run
# 
#   rosrun kingfisher_bringup calibrate_compass
#
# Kingfisher will rotate slowly for 60 seconds and a new calibration will be
# generated.
#
mag_bias:
     x: 0.247656
     y: 0.111936
     z: -0.792586
     radius: 0.310640
